import React from 'react'
import ReactDOM from 'react-dom/client'

// ── Global styles (Tailwind base + CSS reset)
import './index.css'

// ── Import Firebase before App so the SDK initialises before any component mounts
import './firebase'

// ── PWA Service Worker registration
// The SW is generated by vite-plugin-pwa at build time.
// We use workbox-window for a clean, lifecycle-aware registration.
import { registerSW } from 'virtual:pwa-register'

// Register the SW and handle updates silently.
// - `immediate: true` triggers registration right away (not deferred to load event)
// - onNeedRefresh / onOfflineReady give you hooks for UI prompts if needed
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    // New SW is waiting — auto-update silently (registerType: 'autoUpdate' handles this,
    // but we call updateSW(true) as a safety net)
    updateSW(true)
  },
  onOfflineReady() {
    console.info('[CampusTriage] App is ready to work offline.')
  },
  onRegistered(registration) {
    if (registration) {
      console.info('[CampusTriage] Service Worker registered:', registration.scope)
    }
  },
  onRegisterError(error) {
    console.warn('[CampusTriage] Service Worker registration failed:', error)
  },
})

import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
